/*
 * Generated by @ch2ts/core
 * Options: {"emitZod":true}
 */
import { z } from "zod";

export interface Events {
  /** Original: UInt64 */
  id: bigint;
  /** Original: String */
  name: string;
}

export const EventsSchema = z.object({ id: z.bigint(), name: z.string() });
